# Generated by Django 2.2.17 on 2021-01-25 18:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20210124_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 18, 51, 29, 178125, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
