# Generated by Django 2.2.17 on 2021-01-27 21:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20210125_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 21, 31, 33, 268144, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
